global:
  enabled: true
  tlsDisable: false

injector:
  enabled: false

server:
  image:
    tag: "1.18.0"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
  livenessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true
    initialDelaySeconds: 60

  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: proxmox-local-lvm

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: proxmox-local-lvm

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address     = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "HOSTNAME"

          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-2.vault-internal:8200"
          }
        }

        service_registration "kubernetes" {}

  service:
    enabled: true
    type: LoadBalancer
    port: 8200

ui:
  enabled: true
  serviceType: LoadBalancer
  externalPort: 8200
